# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "casyfill@gmail.com"
  - git config --global user.name "Philipp Kats"
script:
  - python setup.py develop && test -w tests/
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
