[tool.poetry]
name = "pycombo"
version = "0.0.1"
description = "Python wrapper around Combo network partitioning algorythm (C++)"
authors = ["Philipp <casyfill@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
networkx = "^2.5"
pytest-cov = "^2.10.1"
python-louvain = "^0.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
