[tool.poetry]
name = "pyCombo"
version = "0.1.0"
description = ""
authors = ["Philipp Kats <casyfill@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
networkx = "^2.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
hypothesis = "^4.44.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# [tool.poetry]
# build = 'build.py'
