[tool.poetry]
name = "pyCombo"
version = "0.0.1"
description = "Python wrapper around Combo network partitioning algorythm (C++)"
authors = ["Philipp <casyfill@gmail.com>"]
license = "MIT"
build = 'build.py'

[tool.poetry.dependencies]
python = "^3.7"
pybind11 = "^2.6.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
networkx = "^2.5"
pytest-cov = "^2.10.1"
python-louvain = "^0.14"
flake8 = "3.8.3"
black = "^20.8b1"

[build-system]
requires = ["setuptools", "wheel", "pybind11==2.6.0"]
build-backend = "setuptools.build_meta"

[tool.pytest]
testpaths = "tests"